### ISSUE TITLE
Atomkraft with provenance binary (help needed)

### ISSUE THREAD

**Issue by ghost** [informalsystems/atomkraft#184]
Hi there,

Trying to setup atomkraft to run with the [provenance](https://github.com/provenance-io/provenance) binary. I have tried few different things but not getting past the following error:

```
👉  atomkraft init provenance-e2e
👉 cd provenance-e2e
👉 atomkraft chain testnet
node id: 655ea20acf1ad2c8db56b1874f3142892375d9b0
Using mainnet defaults
Genesis file created: .atomkraft/validator_nodes/val_q312_lth/node_0/config/genesis.json
Writing app config to: .atomkraft/validator_nodes/val_q312_lth/node_0/config/app.toml ... Done.
Writing tendermint config to: .atomkraft/validator_nodes/val_q312_lth/node_0/config/config.toml ... Done.
Writing client config to: .atomkraft/validator_nodes/val_q312_lth/node_0/config/client.toml ... Done.
Expecting value: line 1 column 1 (char 0)
Exit: 1
```

`chain.toml` looks like this:

```toml
chain_id = "testnet"
validators = 3
accounts = 2
binary = "../provenance/build/provenanced"
hrp_prefix = "provenance"
denom = "hash"
coin_type = 505

[config_node.app]
minimum-gas-prices = "1905hash"
api = { enable = true, swagger = true, enabled-unsafe-cors = true }
rosetta = { enable = false }

[config_node.config]
instrumentation = { prometheus = false }
p2p = { addr_book_strict = false, allow_duplicate_ip = true }

[config_genesis.app_state.gov]
voting_params = { voting_period = "600s" }

[config_genesis.app_state.mint]
minter = { inflation = "0.300000000000000000" }
```

Are there any other logs generated besides above? 😕
